services:
  app:
    build: .
    container_name: iotnarad_app
    ports:
      - "8050:8050"
    env_file:
      - .env
    depends_on:
      - mqtt
    volumes:
      - ./.env:/app/.env:ro
      - ./app:/app/app
      - ./data:/app/data
    restart: unless-stopped

  mqtt:
    image: eclipse-mosquitto:2
    container_name: iotnarad_mqtt
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./infra/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    restart: unless-stopped

  influxdb:
    image: influxdb:2.7
    container_name: iotnarad_influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpassword
      - DOCKER_INFLUXDB_INIT_ORG=iotnarad
      - DOCKER_INFLUXDB_INIT_BUCKET=iotnarad-bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-auth-token
    volumes:
      - influxdb-data:/var/lib/influxdb2
    restart: unless-stopped

volumes:
  influxdb-data:
